# Generated by Django 6.0.6 on 2026-06-13 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('expense_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='Amount exactly as entered/imported in original currency.', max_digits=14)),
                ('original_currency', models.CharField(choices=[('INR', 'INR'), ('USD', 'USD')], default='INR', max_length=3)),
                ('amount_paise', models.BigIntegerField(help_text='Final ledger amount in INR paise.')),
                ('split_type', models.CharField(choices=[('EQUAL', 'Equal'), ('EXACT', 'Exact'), ('PERCENTAGE', 'Percentage'), ('SHARE', 'Share')], max_length=20)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to='imports.importrow')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owed_paise', models.BigIntegerField(help_text='Amount this user owes for this expense in INR paise.')),
                ('raw_value', models.CharField(blank=True, help_text='Original split value from CSV, useful for traceability.', max_length=100)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='expenses.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_splits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount_paise', models.BigIntegerField(help_text='Settlement amount in INR paise.')),
                ('settlement_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='groups.group')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_paid', to=settings.AUTH_USER_MODEL)),
                ('paid_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements_received', to=settings.AUTH_USER_MODEL)),
                ('source_import_row', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_settlements', to='imports.importrow')),
            ],
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'expense_date'], name='expenses_ex_group_i_bce87c_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['group', 'paid_by'], name='expenses_ex_group_i_ae7ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['source_import_row'], name='expenses_ex_source__c5aaa5_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesplit',
            index=models.Index(fields=['user'], name='expenses_ex_user_id_2bb181_idx'),
        ),
        migrations.AddIndex(
            model_name='expensesplit',
            index=models.Index(fields=['expense'], name='expenses_ex_expense_45ede9_idx'),
        ),
        migrations.AddConstraint(
            model_name='expensesplit',
            constraint=models.UniqueConstraint(fields=('expense', 'user'), name='unique_expense_split_per_user'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['group', 'settlement_date'], name='expenses_se_group_i_73677a_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['paid_by', 'paid_to'], name='expenses_se_paid_by_a9cc8b_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['source_import_row'], name='expenses_se_source__bcf1d4_idx'),
        ),
    ]
