# Generated by Django 6.0.6 on 2026-06-13 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_GROUP', 'Create Group'), ('UPDATE_GROUP', 'Update Group'), ('ADD_MEMBER', 'Add Member'), ('UPDATE_MEMBERSHIP', 'Update Membership'), ('REMOVE_MEMBER', 'Remove Member'), ('CREATE_EXPENSE', 'Create Expense'), ('UPDATE_EXPENSE', 'Update Expense'), ('DELETE_EXPENSE', 'Delete Expense'), ('RECORD_SETTLEMENT', 'Record Settlement'), ('UPLOAD_IMPORT', 'Upload Import'), ('REVIEW_IMPORT_ISSUE', 'Review Import Issue'), ('COMMIT_IMPORT', 'Commit Import'), ('AI_EXPLAIN_IMPORT', 'AI Explain Import')], max_length=80)),
                ('entity_type', models.CharField(help_text='Example: Expense, ImportIssue, ImportBatch, GroupMembership', max_length=80)),
                ('entity_id', models.CharField(blank=True, help_text='ID of the entity affected.', max_length=80)),
                ('before', models.JSONField(blank=True, help_text='State before the action.', null=True)),
                ('after', models.JSONField(blank=True, help_text='State after the action.', null=True)),
                ('note', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra context like request source, row number, issue code, etc.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
