import { ArrowRight, Landmark, Network, Scale } from "lucide-react";
import { type SuggestedSettlement } from "./types";
import { StatusBadge } from "../../components/ui/StatusBadge";

type SettlementGraphProps = {
  settlements: SuggestedSettlement[];
};

type GraphNode = {
  name: string;
  x: number;
  y: number;
};

function getInitial(name: string) {
  return name.charAt(0).toUpperCase();
}

function buildNodes(settlements: SuggestedSettlement[]): GraphNode[] {
  const people = Array.from(
    new Set(settlements.flatMap((settlement) => [settlement.from, settlement.to])),
  );

  const centerX = 260;
  const centerY = 180;
  const radiusX = 185;
  const radiusY = 120;

  return people.map((person, index) => {
    const angle = (index / people.length) * Math.PI * 2 - Math.PI / 2;

    return {
      name: person,
      x: centerX + Math.cos(angle) * radiusX,
      y: centerY + Math.sin(angle) * radiusY,
    };
  });
}

function getNode(nodes: GraphNode[], name: string) {
  return nodes.find((node) => node.name === name);
}

export function SettlementGraph({ settlements }: SettlementGraphProps) {
  const nodes = buildNodes(settlements);

  if (!settlements.length) {
    return (
      <div className="glass-panel ring-gradient rounded-3xl p-6">
        <div className="flex items-center gap-3">
          <div className="rounded-2xl border border-ledger-green/20 bg-ledger-green/10 p-3 text-ledger-green">
            <Scale className="h-5 w-5" />
          </div>

          <div>
            <h2 className="font-display text-2xl font-semibold">
              Settlement graph
            </h2>
            <p className="text-sm text-ledger-muted">
              No transfers needed right now.
            </p>
          </div>
        </div>

        <div className="mt-6 rounded-3xl border border-ledger-green/20 bg-ledger-green/10 p-8 text-center">
          <p className="font-display text-3xl font-semibold text-white">
            Everyone is settled.
          </p>
          <p className="mt-3 text-sm leading-6 text-ledger-muted">
            The committed ledger currently has no outstanding debt edges.
          </p>
        </div>
      </div>
    );
  }

  return (
    <div className="glass-panel ring-gradient rounded-3xl p-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <div className="flex items-center gap-3">
          <div className="rounded-2xl border border-ledger-green/20 bg-ledger-green/10 p-3 text-ledger-green">
            <Network className="h-5 w-5" />
          </div>

          <div>
            <h2 className="font-display text-2xl font-semibold">
              Settlement graph
            </h2>
            <p className="text-sm text-ledger-muted">
              Visual debt edges generated by the backend balance engine.
            </p>
          </div>
        </div>

        <StatusBadge tone="violet">
          {`${settlements.length} transfer${settlements.length === 1 ? "" : "s"}`}
        </StatusBadge>
      </div>

      <div className="mt-6 overflow-hidden rounded-3xl border border-white/10 bg-black/20">
        <svg
          viewBox="0 0 520 360"
          role="img"
          aria-label="Suggested settlement graph"
          className="h-[360px] w-full"
        >
          <defs>
            <marker
              id="settlement-arrow"
              markerWidth="10"
              markerHeight="10"
              refX="8"
              refY="3"
              orient="auto"
              markerUnits="strokeWidth"
            >
              <path d="M0,0 L0,6 L9,3 z" fill="rgb(48 226 155 / 0.8)" />
            </marker>

            <filter id="node-glow">
              <feGaussianBlur stdDeviation="4" result="coloredBlur" />
              <feMerge>
                <feMergeNode in="coloredBlur" />
                <feMergeNode in="SourceGraphic" />
              </feMerge>
            </filter>
          </defs>

          <rect width="520" height="360" fill="transparent" />

          {settlements.map((settlement) => {
            const fromNode = getNode(nodes, settlement.from);
            const toNode = getNode(nodes, settlement.to);

            if (!fromNode || !toNode) return null;

            const midX = (fromNode.x + toNode.x) / 2;
            const midY = (fromNode.y + toNode.y) / 2;

            return (
              <g
                key={`${settlement.from}-${settlement.to}-${settlement.amount_paise}`}
              >
                <line
                  x1={fromNode.x}
                  y1={fromNode.y}
                  x2={toNode.x}
                  y2={toNode.y}
                  stroke="rgb(48 226 155 / 0.42)"
                  strokeWidth="2"
                  strokeDasharray="7 7"
                  markerEnd="url(#settlement-arrow)"
                />

                <foreignObject x={midX - 46} y={midY - 18} width="92" height="36">
                  <div className="flex h-9 items-center justify-center rounded-full border border-ledger-green/20 bg-ledger-bg/90 text-xs font-semibold text-ledger-green backdrop-blur">
                    ₹{settlement.amount_rupees}
                  </div>
                </foreignObject>
              </g>
            );
          })}

          {nodes.map((node) => (
            <g key={node.name} filter="url(#node-glow)">
              <circle
                cx={node.x}
                cy={node.y}
                r="34"
                fill="rgb(255 255 255 / 0.06)"
                stroke="rgb(255 255 255 / 0.14)"
                strokeWidth="1"
              />

              <circle
                cx={node.x}
                cy={node.y}
                r="24"
                fill="rgb(48 226 155 / 0.12)"
                stroke="rgb(48 226 155 / 0.35)"
                strokeWidth="1"
              />

              <text
                x={node.x}
                y={node.y + 6}
                textAnchor="middle"
                fill="#f8fafc"
                fontSize="18"
                fontWeight="700"
              >
                {getInitial(node.name)}
              </text>

              <text
                x={node.x}
                y={node.y + 54}
                textAnchor="middle"
                fill="#94a3b8"
                fontSize="12"
              >
                {node.name}
              </text>
            </g>
          ))}
        </svg>
      </div>

      <div className="mt-6 space-y-3">
        {settlements.map((settlement) => (
          <div
            key={`${settlement.from}-${settlement.to}-${settlement.amount_paise}-list`}
            className="rounded-3xl border border-white/10 bg-white/[0.03] p-5"
          >
            <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
              <div className="flex flex-wrap items-center gap-3">
                <div className="rounded-2xl bg-ledger-red/10 px-4 py-3 text-sm font-medium text-ledger-red">
                  {settlement.from}
                </div>

                <ArrowRight className="h-4 w-4 text-ledger-muted" />

                <div className="rounded-2xl bg-ledger-green/10 px-4 py-3 text-sm font-medium text-ledger-green">
                  {settlement.to}
                </div>
              </div>

              <div className="flex items-center gap-3">
                <Landmark className="h-5 w-5 text-ledger-green" />
                <p className="font-display text-2xl font-semibold">
                  ₹{settlement.amount_rupees}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
