# Generated by Django 6.0.6 on 2026-06-13 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('PARTIALLY_COMMITTED', 'Partially Committed'), ('COMMITTED', 'Committed'), ('FAILED', 'Failed')], default='PENDING_REVIEW', max_length=30)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict, help_text='Small summary: counts by severity, valid rows, blocked rows.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='groups.group')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_import_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Machine-readable anomaly code.', max_length=80)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], max_length=20)),
                ('message', models.TextField(help_text='Human-readable explanation shown in import report.')),
                ('policy', models.TextField(blank=True, help_text='Documented policy used to handle this issue.')),
                ('suggested_action', models.CharField(blank=True, help_text='Example: Skip duplicate, Convert USD, Review manually.', max_length=120)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.importbatch')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_import_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImportDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(help_text='APPROVE, REJECT, SKIP_ROW, IMPORT_AS_SETTLEMENT, etc.', max_length=50)),
                ('before', models.JSONField(blank=True, help_text='State before decision.', null=True)),
                ('after', models.JSONField(blank=True, help_text='State after decision.', null=True)),
                ('note', models.TextField(blank=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_decisions', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='imports.importissue')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.PositiveIntegerField(help_text='CSV row number. Header is row 1, data usually starts at row 2.')),
                ('raw_data', models.JSONField(default=dict, help_text='Original CSV row as dictionary.')),
                ('normalized_data', models.JSONField(blank=True, default=dict, help_text='Normalized row after cleaning date/name/currency/split fields.')),
                ('row_hash', models.CharField(db_index=True, help_text='Hash of normalized row, used for exact duplicate detection.', max_length=64)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('NEEDS_REVIEW', 'Needs Review'), ('BLOCKED', 'Blocked'), ('SKIPPED', 'Skipped'), ('COMMITTED', 'Committed')], default='NEEDS_REVIEW', max_length=30)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
            ],
        ),
        migrations.AddField(
            model_name='importissue',
            name='row',
            field=models.ForeignKey(blank=True, help_text='Some batch-level issues may not belong to one specific row.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='imports.importrow'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['group', 'created_at'], name='imports_imp_group_i_8c9e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='imports_imp_uploade_f30c09_idx'),
        ),
        migrations.AddIndex(
            model_name='importbatch',
            index=models.Index(fields=['status'], name='imports_imp_status_22f3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'status'], name='imports_imp_batch_i_4b8c02_idx'),
        ),
        migrations.AddIndex(
            model_name='importrow',
            index=models.Index(fields=['batch', 'row_hash'], name='imports_imp_batch_i_dab2e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='importrow',
            constraint=models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_import_row_number_per_batch'),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['batch', 'severity'], name='imports_imp_batch_i_9cabe6_idx'),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['batch', 'status'], name='imports_imp_batch_i_ff1e11_idx'),
        ),
        migrations.AddIndex(
            model_name='importissue',
            index=models.Index(fields=['code'], name='imports_imp_code_998e59_idx'),
        ),
    ]
